
pipeline {
    agent any
    environment {
        // Define any environment variables here
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_IMAGE = 'myapp:latest'
    }
    stages {
        // This stage is to get the source codes for our project from github
        stage('Git Checkout') {
            steps {
                // if we don't specify the dir() directive, then all the contents of website repo will be directly copied to jenkins job dir root dir 
                // '$JENKINS_HOME/workspace/Job/'. so, here we create separate folders for eache repo we want to copy. Here, it will create two folders website and cicd

                dir('website') {
                        git 'https://github.com/SambhuBiswakarma00/website.git'
                    }
                    
                    dir('cicd') {
                        git 'https://github.com/SambhuBiswakarma00/Complete-CICD-with-Jenkins.git'
                    }
            }
        }

        stage('SonarQube Analsyis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=myApp -Dsonar.projectKey=myApp \
                            -Dsonar.sources=website 
                    '''
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                script {
                  waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            }
        }
        
        
        
        stage('Build & Tag Docker Image') {
            steps {
               script {
                   withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                            sh "docker build -t sambhubiswakarma00/myApp:latest website"
                    }
               }
            }
        }
        
        stage('Docker Image Scan') {
            steps {
                sh "trivy image --format table -o trivy-myApp-image-report.html sambhubiswakarma00/myApp:latest "
            }
        }
        
        stage('Push Docker Image') {
            steps {
               script {
                   withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                            sh "docker push sambhubiswakarma00/myApp:latest"
                    }
               }
            }
        }
        stage('Deploy To Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: 'kubernetes', contextName: '', credentialsId: 'k8-cred', namespace: 'myApp', restrictKubeConfigAccess: false, serverUrl: 'https://172.31.8.146:6443') {
                            sh "kubectl apply -f cicd/kubernetes/deployment.yaml"
                            sh "kubectl apply -f cicd/kubernetes/service.yaml"
                }
            }
        }
        
        stage('Verify the Deployment') {
            steps {
               withKubeConfig(caCertificate: '', clusterName: 'kubernetes', contextName: '', credentialsId: 'k8-cred', namespace: 'myApp', restrictKubeConfigAccess: false, serverUrl: 'https://172.31.8.146:6443') {
                        sh "kubectl get pods -n myApp"
                        sh "kubectl get svc -n myApp"
                }
            }
        }
        
        
    }
    post {
        always {
            script {
                def jobName = env.JOB_NAME
                def buildNumber = env.BUILD_NUMBER
                def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
                def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'

                def body = """
                    <html>
                    <body>
                    <div style="border: 4px solid ${bannerColor}; padding: 10px;">
                    <h2>${jobName} - Build ${buildNumber}</h2>
                    <div style="background-color: ${bannerColor}; padding: 10px;">
                    <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
                    </div>
                    <p>Check the <a href="${BUILD_URL}">console output</a>.</p>
                    </div>
                    </body>
                    </html>
                """

                emailext (
                    subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
                    body: body,
                    to: 'B170026@nitsikkim.ac.in',
                    from: 'biswakarmasambhu@gmail.com',
                    replyTo: 'biswakarmasambhu@gmail.com'',
                    mimeType: 'text/html',
                    attachmentsPattern: 'trivy-myApp-image-report.html'
                )
            }
        }
    }
}
