apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-role-binding
  namespace: myApp-ns
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: myApp-ns
roleRef:
  kind: Role
  name: jenkins-admin-role
  apiGroup: rbac.authorization.k8s.io
