--- 
# - hosts: master_node
#   remote_user: ubuntu
#   become: 'yes'
#   roles:
#     - Roles/clusterConfiguration

- hosts: tools_instance
  remote_user: ubuntu
  become: 'yes'
  roles:
    - Roles/toolsInstanceConfig





