--- 
- name: Play 1, installing necessary softwares on master server
  hosts: master
  remote_user: ubuntu
  become: 'yes'
  tasks:
    - name: Installing java on this test node for jenkins master-slave dependencies 
      script: installs/java_install.sh
    - name: Installing kube on this test node 
      script: installs/kube_install.sh
    - name: Copying kubernetes files on test-server 
      copy: src=../kubernetes dest=/home/ubuntu/

- name: Play 2, installing necessary softwares on slave-1 server
  hosts: slave1
  remote_user: ubuntu
  become: 'yes'
  tasks:
    - name: Installing java on this prod node for jenkins master-slave dependencies 
      script: installs/java_install.sh
    - name: Installing kube on this prod node 
      script: installs/kube_install.sh 
    - name: copying kubernetes files on slave-1 server   
      copy: src=../kubernetes dest=/home/ubuntu/

- name: Play 3, installing necessary softwares on slave-2 server
  hosts: slave2
  remote_user: ubuntu
  become: 'yes'
  tasks:
    - name: Installing java on this prod node for jenkins master-slave dependencies 
      script: installs/java_install.sh
    - name: Installing kube on this prod node 
      script: installs/kube_install.sh 
    - name: copying kubernetes files on slave-2 server   
      copy: src=../kubernetes dest=/home/ubuntu/