--- 
# - hosts: cluster_all_nodes
#   remote_user: ubuntu
#   become: 'yes'
#   roles:
#     - clusterConfiguration

- hosts: tools_instance
  remote_user: ubuntu
  become: 'yes'
  roles:
    - Roles/toolsInstanceConfig





