--- 
- hosts: apache_server_group
  remote_user: ubuntu
  become: 'yes'
  roles:
    - clusterConfiguration

- hosts: nginx_server_group
  remote_user: ubuntu
  become: 'yes'
  roles:
    - toolsInstanceConfig





